### ISSUE TITLE
Build / Install issue

### ISSUE THREAD

**Issue by carnak** [microsoft/msticpy-training#17]
Hello, am getting following error on initial build / install - everything seems to have went fine, up until:

#4 161.1 [I 13:43:49 InstallContribNbextensionsApp] - Validating: OK
#4 161.1 [I 13:43:49 InstallContribNbextensionsApp] Installing jupyter_contrib_nbextensions items to config in /opt/conda/etc/jupyter
#4 161.1 Enabling: jupyter_nbextensions_configurator
#4 161.1 - Writing config: /opt/conda/etc/jupyter
#4 161.1     - Validating...
#4 161.1       jupyter_nbextensions_configurator 0.6.1 OK
#4 161.1 Enabling notebook nbextension nbextensions_configurator/config_menu/main...
#4 161.1 Enabling tree nbextension nbextensions_configurator/tree_tab/main...
#4 161.1 [I 13:43:49 InstallContribNbextensionsApp] Enabling notebook extension contrib_nbextensions_help_item/main...
#4 161.1 [I 13:43:49 InstallContribNbextensionsApp]       - Validating: OK
#4 161.1 [I 13:43:49 InstallContribNbextensionsApp] - Editing config: /opt/conda/etc/jupyter/jupyter_nbconvert_config.json
#4 161.1 [I 13:43:49 InstallContribNbextensionsApp] --  Configuring nbconvert template path
#4 161.1 [I 13:43:49 InstallContribNbextensionsApp] --  Configuring nbconvert preprocessors
#4 161.1 [I 13:43:49 InstallContribNbextensionsApp] - Writing config: /opt/conda/etc/jupyter/jupyter_nbconvert_config.json
#4 161.1 [I 13:43:49 InstallContribNbextensionsApp] --  Writing updated config file /opt/conda/etc/jupyter/jupyter_nbconvert_config.json
#4 175.3
#4 175.3 done
#4 175.3 ERROR conda.core.link:_execute(740): An error occurred while installing package 'conda-forge::rise-5.7.1-py310hff52083_2'.
#4 175.3 Rolling back transaction: ...working... done
#4 178.0
#4 178.0 LinkError: post-link script failed for package conda-forge::rise-5.7.1-py310hff52083_2
#4 178.0 location of failed script: /opt/conda/bin/.rise-post-link.sh
#4 178.0 ==> script messages <==
#4 178.0 <None>
#4 178.0 ==> script output <==
#4 178.0 stdout:
#4 178.0 stderr: Traceback (most recent call last):
#4 178.0   File "/opt/conda/bin/jupyter-nbextension", line 10, in <module>
#4 178.0     sys.exit(main())
#4 178.0   File "/opt/conda/lib/python3.10/site-packages/jupyter_core/application.py", line 277, in launch_instance
#4 178.0     return super().launch_instance(argv=argv, **kwargs)
#4 178.0   File "/opt/conda/lib/python3.10/site-packages/traitlets/config/application.py", line 1041, in launch_instance#4 178.0     app.start()
#4 178.0   File "/opt/conda/lib/python3.10/site-packages/notebook/nbextensions.py", line 972, in start
#4 178.0     super().start()
#4 178.0   File "/opt/conda/lib/python3.10/site-packages/jupyter_core/application.py", line 266, in start
#4 178.0     self.subapp.start()
#4 178.0   File "/opt/conda/lib/python3.10/site-packages/notebook/nbextensions.py", line 882, in start
#4 178.0     self.toggle_nbextension_python(self.extra_args[0])
#4 178.0   File "/opt/conda/lib/python3.10/site-packages/notebook/nbextensions.py", line 855, in toggle_nbextension_python
#4 178.0     return toggle(module,
#4 178.0   File "/opt/conda/lib/python3.10/site-packages/notebook/nbextensions.py", line 470, in enable_nbextension_python
#4 178.0     return _set_nbextension_state_python(True, module, user, sys_prefix,
#4 178.0   File "/opt/conda/lib/python3.10/site-packages/notebook/nbextensions.py", line 368, in _set_nbextension_state_python
#4 178.0     m, nbexts = _get_nbextension_metadata(module)
#4 178.0   File "/opt/conda/lib/python3.10/site-packages/notebook/nbextensions.py", line 1107, in _get_nbextension_metadata
#4 178.0     m = import_item(module)
#4 178.0   File "/opt/conda/lib/python3.10/site-packages/traitlets/utils/importstring.py", line 38, in import_item
#4 178.0     return __import__(parts[0])
#4 178.0   File "/opt/conda/lib/python3.10/site-packages/rise/__init__.py", line 3, in <module>
#4 178.0     __version__ = pkg_resources.require("rise")[0].version
#4 178.0   File "/opt/conda/lib/python3.10/site-packages/pkg_resources/__init__.py", line 909, in require
#4 178.0     needed = self.resolve(parse_requirements(requirements))
#4 178.0   File "/opt/conda/lib/python3.10/site-packages/pkg_resources/__init__.py", line 795, in resolve
#4 178.0     raise DistributionNotFound(req, requirers)
#4 178.0 pkg_resources.DistributionNotFound: The 'webcolors>=1.11; extra == "format-nongpl"' distribution was not found and is required by jsonschema
#4 178.0
#4 178.0 return code: 1
#4 178.0
#4 178.0 ()
#4 178.0
------
executor failed running [/bin/bash -o pipefail -c conda install --quiet --yes ${INSTALL_CONDA_PACKAGES} &&     pip install --upgrade --quiet ${INSTALL_PIP_PACKAGES} &&     git clone https://github.com/microsoft/msticpy.git &&     git clone https://github.com/microsoft/msticpy-training.git &&     pip install --requirement /home/jovyan/msticpy/requirements-all.txt]: exit code: 1

**Comment by carnak** [comment]
here's specific problem installing the "rise" component:

LinkError: post-link script failed for package conda-forge::rise-5.7.1-py310hff52083_2
location of failed script: /opt/conda/bin/.rise-post-link.sh
==> script messages <==
<None>
==> script output <==
stdout:
stderr: Traceback (most recent call last):
  File "/opt/conda/bin/jupyter-nbextension", line 10, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.10/site-packages/jupyter_core/application.py", line 277, in launch_instance
    return super().launch_instance(argv=argv, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/traitlets/config/application.py", line 1041, in launch_instance
    app.start()
  File "/opt/conda/lib/python3.10/site-packages/notebook/nbextensions.py", line 972, in start
    super().start()
  File "/opt/conda/lib/python3.10/site-packages/jupyter_core/application.py", line 266, in start
    self.subapp.start()
  File "/opt/conda/lib/python3.10/site-packages/notebook/nbextensions.py", line 882, in start
    self.toggle_nbextension_python(self.extra_args[0])
  File "/opt/conda/lib/python3.10/site-packages/notebook/nbextensions.py", line 855, in toggle_nbextension_python
    return toggle(module,
  File "/opt/conda/lib/python3.10/site-packages/notebook/nbextensions.py", line 470, in enable_nbextension_python
    return _set_nbextension_state_python(True, module, user, sys_prefix,
  File "/opt/conda/lib/python3.10/site-packages/notebook/nbextensions.py", line 368, in _set_nbextension_state_python
    m, nbexts = _get_nbextension_metadata(module)
  File "/opt/conda/lib/python3.10/site-packages/notebook/nbextensions.py", line 1107, in _get_nbextension_metadata
    m = import_item(module)
  File "/opt/conda/lib/python3.10/site-packages/traitlets/utils/importstring.py", line 38, in import_item
    return __import__(parts[0])
  File "/opt/conda/lib/python3.10/site-packages/rise/__init__.py", line 3, in <module>
    __version__ = pkg_resources.require("rise")[0].version
  File "/opt/conda/lib/python3.10/site-packages/pkg_resources/__init__.py", line 909, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/opt/conda/lib/python3.10/site-packages/pkg_resources/__init__.py", line 795, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'webcolors>=1.11; extra == "format-nongpl"' distribution was not found and is required by jsonschema

return code: 1

()

jovyan@5a75229e3429:/home$

**Comment by carnak** [comment]
Also, on line 8 of Dockerfile, this path doesn't exist in the container i am running:

# Add conda to path
ENV PATH /opt/conda/envs/env/bin:$PATH

/opt/conda/bin does exist.

**Comment by carnak** [comment]
Here is a file compare on changes to the Dockerfile that got me going - 

Comparing files Dockerfile and DOCKERFILE-WORKING
***** Dockerfile
# Add conda to path
ENV PATH /opt/conda/envs/env/bin:$PATH

***** DOCKERFILE-WORKING
# Add conda to path
ENV PATH /opt/conda/bin:$PATH

*****

***** Dockerfile
# Environment variable for Pip and conda packages to be installed
ENV INSTALL_CONDA_PACKAGES jupyter_contrib_nbextensions jupyterthemes phantomjs autopep8 plotly black rise
ENV INSTALL_PIP_PACKAGES azure-cli jupyterlab-git setuptools_git
***** DOCKERFILE-WORKING
# Environment variable for Pip and conda packages to be installed
ENV INSTALL_CONDA_PACKAGES webcolors uri-template rfc3986-validator rfc3339-validator jsonpointer isoduration fqdn jupyter_cont
rib_nbextensions jupyterthemes phantomjs autopep8 plotly black rise
ENV INSTALL_PIP_PACKAGES azure-cli jupyterlab-git setuptools_git
*****

Many thanks to Ian and all the folks who make msticpy possible.

**Comment by carnak** [comment]
Here is a file compare on changes to the Dockerfile that got me going - 

Comparing files Dockerfile and DOCKERFILE-WORKING
***** Dockerfile
# Add conda to path
ENV PATH /opt/conda/envs/env/bin:$PATH

***** DOCKERFILE-WORKING
# Add conda to path
ENV PATH /opt/conda/bin:$PATH

*****

***** Dockerfile
# Environment variable for Pip and conda packages to be installed
ENV INSTALL_CONDA_PACKAGES jupyter_contrib_nbextensions jupyterthemes phantomjs autopep8 plotly black rise
ENV INSTALL_PIP_PACKAGES azure-cli jupyterlab-git setuptools_git
***** DOCKERFILE-WORKING
# Environment variable for Pip and conda packages to be installed
ENV INSTALL_CONDA_PACKAGES webcolors uri-template rfc3986-validator rfc3339-validator jsonpointer isoduration fqdn jupyter_cont
rib_nbextensions jupyterthemes phantomjs autopep8 plotly black rise
ENV INSTALL_PIP_PACKAGES azure-cli jupyterlab-git setuptools_git
*****

Many thanks to Ian and all the folks who make msticpy possible.
